# Generated by Django 5.2.10 on 2026-02-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ganancia_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=40.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
    ]
