# Generated by Django 5.2.10 on 2026-02-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_ganancia_porcentaje_producto_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
