# Generated by Django 5.2.10 on 2026-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='factor_division',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='se_pide_en_unidad_medida',
            field=models.CharField(blank=True, default='kg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='se_vende_en_unidad_medida',
            field=models.CharField(blank=True, default='cajas', max_length=50, null=True),
        ),
    ]
