# Generated by Django 5.2.10 on 2026-01-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        ('pedido', '0001_initial'),
        ('producto', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('en_respuesta_a_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(blank=True, default='kg', max_length=50, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('precio_de_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia_deseada', models.DecimalField(blank=True, decimal_places=2, default=40.0, max_digits=5, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'db_table': 'compra_productos',
            },
        ),
    ]
