# Generated by Django 5.2.10 on 2026-01-29 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraproducto',
            name='estado',
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='estado_compra',
            field=models.CharField(choices=[('comprado', 'Comprado'), ('no_comprado', 'No Comprado')], default='comprado', max_length=50),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='motivo_no_compra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='pedido_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedidoproducto'),
        ),
    ]
