# Generated by Django 5.2.10 on 2026-02-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0002_producto_ganancia_porcentaje_producto_precio_compra'),
        ('usuarios', '0003_alter_usuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('completado', 'Completado')], default='en_proceso', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'pedido_diarios',
            },
        ),
        migrations.CreateModel(
            name='PedidoDiarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(max_length=50)),
                ('estado_compra', models.CharField(choices=[('comprado', 'Comprado'), ('no_comprado', 'No Comprado')], max_length=50)),
                ('motivo_no_compra', models.CharField(blank=True, max_length=255, null=True)),
                ('pedido_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido_diario.pedidodiario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'db_table': 'pedido_diario_items',
                'unique_together': {('pedido_diario', 'producto', 'unidad_medida')},
            },
        ),
    ]
