# Generated by Django 5.2.10 on 2026-02-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodiarioitem',
            name='factor_division',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pedidodiarioitem',
            name='ganancia_aplicada',
            field=models.FloatField(default=40.0),
        ),
        migrations.AddField(
            model_name='pedidodiarioitem',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=10, null=True),
        ),
    ]
