# Generated by Django 5.2.10 on 2026-02-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_diario', '0002_pedidodiarioitem_factor_division_and_more'),
        ('producto', '0004_producto_factor_division_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidodiarioitem',
            unique_together={('pedido_diario', 'producto')},
        ),
        migrations.RemoveField(
            model_name='pedidodiarioitem',
            name='factor_division',
        ),
        migrations.RemoveField(
            model_name='pedidodiarioitem',
            name='ganancia_aplicada',
        ),
        migrations.RemoveField(
            model_name='pedidodiarioitem',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='pedidodiarioitem',
            name='unidad_medida',
        ),
    ]
