# Generated by Django 5.2.10 on 2026-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_diario', '0003_alter_pedidodiarioitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodiarioitem',
            name='factor_division',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Factor de división usado ese día', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidodiarioitem',
            name='ganancia_aplicada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de ganancia aplicado ese día', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedidodiarioitem',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra del producto ese día', max_digits=10, null=True),
        ),
    ]
