# Generated by Django 5.2.10 on 2026-02-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='unidad_medida',
        ),
    ]
