# Generated by Django 5.2.10 on 2026-02-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_remove_pedidoproducto_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='unidad_medida',
            field=models.CharField(default='cajas', max_length=20),
        ),
    ]
